version: "3"
name: "developer"
services:
  webproxy:
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certificate:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: developer.webproxy
  certificate:
    image: jamesblanksby/nginx-proxy-selfsigned-companion
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=developer.webproxy
    volumes:
      - certificate:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - webproxy
    container_name: developer.certificate
  php-7:
    build:
      context: .
      dockerfile: ./dockerfile/php-7
    image: php-7
    restart: unless-stopped
    ports:
      - 59339:80
    environment:
      - DOCKER=true
      - VIRTUAL_HOST=127.0.0.1,localhost,local
      - VIRTUAL_PORT=80
    volumes:
      - ./../:/var/www/html
    container_name: developer.php-7
  php-8:
    build:
      context: .
      dockerfile: ./dockerfile/php-8
    image: php-8
    restart: unless-stopped
    ports:
      - 81:80
    environment:
      - DOCKER=true
    volumes:
      - ./../:/var/www/html
    container_name: developer.php-8
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    platform: linux/amd64
    container_name: developer.mysql
networks:
  default:
    name: webproxy
    external: true
volumes:
  certificate:
    name: developer.certificate
