#!/usr/bin/env bash

open -a Docker

while ! docker stats --no-stream &> /dev/null; do
    sleep 1
done

docker network create -d bridge developer.webproxy && docker-compose -f "$DOTFILES_DIR_HOME/Developer/.docker/compose.yaml" up -d
