#!/usr/bin/env bash

# Process Homebrew formulae

echo "> Processing Homebrew formulae"

if test ! "$(which brew)"; then
    # Install Homebrew
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fLsS https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if [[ "$(uname -m)" == "arm64" ]]; then
        echo "export PATH=\"/opt/homebrew/bin:\$PATH\";" >> "$HOME/.path"
    fi
else
    # Fetch latest version
    brew update --quiet

    # Upgrade outdated formulae
    brew upgrade --quiet
fi

# Homebrew's install location
PREFIX="$(brew --prefix)"

# Latest version of Bash
brew install --quiet bash
brew install --quiet bash-completion@2

# Switch to using Homebrew installed Bash as default shell
if ! fgrep -q "${PREFIX}/bin/bash" "/etc/shells"; then
    echo "${PREFIX}/bin/bash" | sudo tee -a "/etc/shells"
    chsh -s "${PREFIX}/bin/bash"
fi;

# Window manager
brew install --quiet --cask rectangle

# Useful formulae
brew install --quiet git
brew install --quiet rsync
brew install --quiet wget
brew install --quiet ffmpeg
brew install --quiet nano
brew install --quiet exiftool
