#!/usr/bin/env bash

# Process Homebrew formulae

echo "> Processing Homebrew formulae"

if test ! "$(which brew)"; then
    # Install Homebrew
    echo | /bin/bash -c "$(curl -fLsS https://raw.githubusercontent.com/Homebrew/install/master/install.sh > /dev/null)"
    if [[ "$(uname -m)" == "arm64" ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
else
    # Fetch latest version
    brew update

    # Upgrade outdated formulae
    brew upgrade
fi

# Homebrew's install location
PREFIX="$(brew --prefix)"

# Latest version of Bash
brew install -quiet bash
brew install -quiet bash-completion@2

# Switch to using Homebrew install -quieted Bash as default shell
if ! fgrep -q "${PREFIX}/bin/bash" "/etc/shells"; then
    echo "${PREFIX}/bin/bash" | sudo tee -a "/etc/shells"
    chsh -s "${PREFIX}/bin/bash"
fi;

# Window manager
brew install -quiet --cask rectangle

# Useful formulae
brew install -quiet git
brew install -quiet rsync
brew install -quiet wget
brew install -quiet ffmpeg
brew install -quiet nano
brew install -quiet exiftool
