#!/usr/bin/env bash

cd ~/Downloads

git pull origin master

function execute() {
    rsync -avh \
        --no-perms \
        --exclude ".git/" \
        --exclude ".DS_Store" \
        --exclude "README.md" \
        --exclude "macos" \
        --exclude "brew" \
        --exclude "yarn" \
        . ~
    source ~/.bash_profile
    ./macos
    ./brew
    ./yarn
}

read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) "
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    execute
fi;