#!/usr/bin/env bash

# Install command line tools using Homebrew

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing sudo timestamp until brew has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Home-brew
if [[ $(command -v brew) == "" ]]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Fetch the newest version
brew update

# Upgrade outdated formulae
brew upgrade

# Store Homebrew's install location
BREW_PREFIX=$(brew --prefix)

# Install a modern version of Bash
brew install bash
brew install bash-completion2

# Added Homebrew Bash shell to available shells
if ! fgrep -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
    echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
fi;

# Switch to using Homebrew installed Bash as default shell
chsh -s "${BREW_PREFIX}/bin/bash";

# Install development tools
brew cask install docker
brew install mysql
brew install composer
brew install node
brew install yarn

# Install other useful binaries
brew install git
brew install git-lfs
brew install rsync
brew install iperf
brew install wget
brew install sqlite
brew install ffmpeg

# Remove old versions of installed formula
brew cleanup
