#!/usr/bin/env bash

# Install command line tools using Homebrew

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing sudo timestamp until brew has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Home-brew
if [[ $(command -v brew) == "" ]]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# Fetch the newest version
brew update

# Upgrade outdated formulae
brew upgrade

# Store Homebrew's install location
BREW_PREFIX=$(brew --prefix)

# Install a modern version of Bash
brew install bash
brew install bash-completion2

# Add Homebrew Bash to available shells
if ! fgrep -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
    echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
fi;

# Switch to using Homebrew installed Bash as default shell
chsh -s "${BREW_PREFIX}/bin/bash";

# Install development tools
brew install --cask docker
brew install mysql@5.7 && brew link --force mysql@5.7
brew install composer
brew install node
brew install yarn

# Install GPG tools
brew install gnupg
brew install pinentry-mac

# Setup GPG to use pinentry
mkdir -m 700 -p ~/.gnupg && echo "pinentry-program ${BREW_PREFIX}/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf && killall gpg-agent

# Install window manager
brew install --cask rectangle

# Install other useful binaries
brew install git
brew install git-lfs
brew install rsync
brew install iperf
brew install wget
brew install sqlite
brew install ffmpeg
brew install nano

# Start required services
brew services start mysql@5.7

# Remove old versions of installed formula
brew cleanup
