#!/usr/bin/env bash

# Install command line tools using Homebrew

# Install Home-brew
if [[ $(command -v brew) == "" ]]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

exit

# Fetch the newest version
brew update

# Upgrade outdated formulae
brew upgrade

# Store Homebrew's install location
BREW_PREFIX=$(brew --prefix)

# Install a modern version of Bash
brew install bash
brew install bash-completion2

# Switch to using Homebrew installed Bash as default shell
if ! fgrep -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
    echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
    chsh -s "${BREW_PREFIX}/bin/bash";
fi;

# Install development tools
brew install docker
brew install composer
brew install yarn

# Install other useful binaries
brew install git
brew install git-lfs
brew install rsync

# Remove old versions of installed formula
brew cleanup
