#!/usr/bin/env bash

source $(dirname $0)/utility

function execute() {
    echo "⚙️  Setting up a $SETUP system configuration:"

    divider

    # Bootstrap scripts
    bootstrap

    # Add setup type export
    echo -e "\n# Dotfiles setup type\nexport DOTFILES_SETUP=$SETUP" >> "$HOME/.exports"

    # Initialise profile
    source "$HOME/.bash_profile"

    # Success message
    echo "✅ Install complete"
}

# Validate existing install
if [[ -v $DOTFILES_SETUP ]]; then
    echo "⛔️ Dotfiles already installed"

    exit
fi

# Ask for the administrator password upfront
sudo -v

# Update existing sudo timestamp until install has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

divider

# Choose setup type
echo "🛠️  What kind of setup do you want to create?"
echo "1. Personal (default)"
echo "2. Developer"
read -p "Option: " SETUP

# Validate setup type
case $SETUP in
    1) SETUP="personal" ;;
    2) SETUP="developer" ;;
    *) SETUP="personal" ;;
esac

divider

# Overwrite file warning
echo "⚠️  This will overwrite existing files in your home directory."
read -p "Are you sure? (y/n): "

divider

# Validate positive reply
if [[ $REPLY =~ ^[Yy]$ ]]; then
    execute
fi

exit
