#!/usr/bin/env bash

# Close any open System Preferences panes to prevent overriding
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing sudo timestamp until macos has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Check whether Terminal has Full Disk Access
if [[ ! -r "/Library/Application Support/com.apple.TCC/TCC.db" ]]; then
    echo "Full Disk Access must be granted to Terminal in order to run this script."
    open "x-apple.systempreferences:com.apple.preference.security?Privacy"
    exit
fi


## GENERAL UI/UX ##

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -bool true
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Show battery percentage in menu bar
defaults write com.apple.menuextra.battery ShowPercent -bool true

# Set sidebar icon size to small
defaults write -g NSTableViewDefaultSizeMode -int 1

# Expand save panel by default
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true

# Expand print panel by default
defaults write -g PMPrintingExpandedStateForPrint -bool true

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable smart substitutions as they’re annoying when typing code
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable automatic capitalisation as it’s annoying when typing code
defaults write -g NSAutomaticCapitalizationEnabled -bool false

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName


## TRACKPAD, MOUSE, KEYBOARD AND INPUT ##

# Enable tap to click 
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write -g com.apple.mouse.tapBehavior -bool true

# Set trackpad/mouse tracking speed
defaults write -g com.apple.trackpad.scaling 3
defaults write -g com.apple.mouse.scaling 5


## ENERGY SAVING ##

# Enable lid wakeup
sudo pmset -a lidwake 1

# Restart automatically on power loss
sudo pmset -a autorestart 1

# Sleep the display after 15 minutes
sudo pmset -a displaysleep 15

# Disable machine sleep while charging
sudo pmset -c sleep 0 &> /dev/null

# Set machine sleep to 5 minutes on battery
sudo pmset -b sleep 5 &> /dev/null

# Set standby delay to 24 hours (default is 1 hour)
sudo pmset -a standbydelay 86400

# Never go into computer sleep mode
sudo systemsetup -setcomputersleep Off > /dev/null

# Restart automatically if the computer freezes
sudo systemsetup -setrestartfreeze on


## DOCK AND HOT CORNERS ##

# Set the icon size of Dock items
defaults write com.apple.dock tilesize -int 40
defaults write com.apple.Dock size-immutable -bool true

# Disable Dock item magnification
defaults write com.apple.dock magnification -bool false

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Disable recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Enable spring loading for all Dock items
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

# Set top right screen hot corner to Desktop 
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0


## FINDER ##

# Set Finder sidebar width
defaults write com.apple.finder SidebarWidth 125

# Show Finder status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Show finder path bar
defaults write com.apple.finder ShowPathbar -bool true

# Use list view in all Finder windows by default
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Reduce the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0.25

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Set Downloads as the default location for new Finder windows
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Downloads/"

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Show the ~/Library folder
sudo chflags nohidden ~/Library

# Show the /Volumes folder
sudo chflags nohidden /Volumes

defaults write com.apple.finder FXInfoPanesExpanded -dict \
    General -bool true \
    MetaData -bool true \
    OpenWith -bool true \
    Preview -bool true \
    Privileges -bool true


## SPOTLIGHT ##

# Disable Spotlight indexing for any volume that gets mounted
sudo defaults write /Library/Preferences/com.apple.SpotlightServer.plist ExternalVolumesIgnore -bool True


## TERMINAL ##

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# Set Terminal theme
osascript <<EOD

tell application "Terminal"
    local windowAll
    local windowInitial
    local windowID

    set themeName to "Toy Chest"
    set scriptDir to (path to me as string)

    (* Store the IDs of all the open terminal windows. *)
    set windowInitial to id of every window

    (* Open the custom theme so that it gets added to the list
       of available terminal themes (note: this will open two
       additional terminal windows). *)
    do shell script "open 'store/" & themeName & ".terminal'"

    (* Wait a little bit to ensure that the custom theme is added. *)
    delay 1

    (* Set the custom theme as the default terminal theme. *)
    set default settings to settings set themeName

    (* Get the IDs of all the currently opened terminal windows. *)
    set windowAll to id of every window

    repeat with windowID in windowAll
        (* Close the additional windows that were opened in order
           to add the custom theme to the list of terminal themes. *)
        if windowInitial does not contain windowID then
            close (every window whose id is windowID)
            (* Change the theme for the initial opened terminal windows
           to remove the need to close them in order for the custom
           theme to be applied. *)
        else
            set current settings of tabs of (every window whose id is windowID) to settings set themeName
        end if
    end repeat
end tell

EOD


## MAIL ##

# Display most recent message at the top
defaults write com.apple.mail ConversationViewSortDescending -bool true

# Disable inline attachments (just show the icons)
defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

# Copy email addresses as foo@example.com instead of Foo Bar <foo@example.com> in Mail.app
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false


## GOOGLE CHROME ##

# Disable sensitive backswipe
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false

# Use the system-native print preview dialog
defaults write com.google.Chrome DisablePrintPreview -bool true

# Expand the print dialog by default
defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true


## TEXTEDIT ##

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -bool false

# Open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4


## APP STORE ##

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

# Allow the App Store to reboot machine on macOS updates
defaults write com.apple.commerce AutoUpdateRestartRequired -bool true


## PHOTOS ##

# Prevent Photos from opening automatically when devices are plugged in
defaults write com.apple.ImageCapture disableHotPlug -bool true


## CALENDAR ##

# Show week numbers
defaults write com.apple.iCal "Show Week Numbers" -bool true

# Make text smaller
defaults write com.apple.iCal CalUICanvasOccurrenceFontSize -int 10



echo "Complete. Restarting in 10 seconds to allow changes to take effect."
sudo shutdown -h +10
