#!/usr/bin/env bash

source "$(dirname "$0")/utility"

function execute() {
    echo "⚙️  Updating $SETUP system configuration:"

    divider

    bootstrap

    echo "✅ Update complete"
}

# Validate existing install
if [[ -z ${DOTFILES_SETUP+x} ]]; then
    echo "⛔️ Dotfiles not installed"

    exit
fi

# Setup type
SETUP=$DOTFILES_SETUP

superuser

divider

# Overwrite file warning
echo "⚠️  This will overwrite existing files in your home directory."
read -rp "Are you sure? (y/n): "

divider

# Validate positive reply
if [[ $REPLY =~ ^[Yy]$ ]]; then
    execute
fi

exit
