#!/usr/bin/env bash

function superuser() {
    # Keep sudo alive
    sudo -v
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

function divider() {
    printf "%*s\n" "${COLUMNS:-$(tput cols)}" "" | tr " " -
}

function bootstrap() {
    # Global scripts
    for file in ./bootstrap/*; do
        [ -f "$file" ] && source "$file"
    done

    # Setup scripts
    for file in ./bootstrap/$SETUP/*; do 
        [ -f "$file" ] && source "$file"
    done

    # Add setup type export
    echo -e "\n# Dotfiles setup type\nexport DOTFILES_SETUP=$SETUP" >> "$HOME/.exports"

    # Initialize profile
    source "$HOME/.bash_profile"
}
