#!/usr/bin/env bash

# Move configuration files

echo "> Moving configuration files"

# cp ./config/developer/my.cnf $([ -d "/opt/homebrew/etc" ] && echo "/opt/homebrew/etc/my.cnf" || echo "/usr/local/etc/my.cnf")
