#!/usr/bin/env bash

# Create development server setup

echo "> Creating development server setup"

# directory="$HOME/Developer"

# if [ ! -d "$directory" ]; then
#     mkdir "$directory"
# fi

# rsync -aqh \
#     --no-perms \
#     "./storage/Developer/" "$directory/"
