#!/usr/bin/env bash

# Process Homebrew formulae

echo "> Processing developer Homebrew formulae"

# Homebrew's install location
PREFIX="$(brew --prefix)"

# GPG tools
brew install -quiet gnupg
brew install -quiet pinentry-mac

# Setup GPG to use pinentry
mkdir -m 700 -p "$HOME/.gnupg" \
    && echo "pinentry-program ${PREFIX}/bin/pinentry-mac" > "$HOME/.gnupg/gpg-agent.conf" \
    && killall gpg-agent

# Development tools
brew install -quiet --cask docker
brew install -quiet docker-compose
brew install -quiet mysql@5.7 && brew link --force mysql@5.7
brew install -quiet composer
brew install -quiet node
brew install -quiet yarn

# Useful formulae
brew install -quiet shellcheck
brew install -quiet git-lfs

# Start required services
brew services start mysql@5.7
