#!/usr/bin/env bash

# Install Docker network loopback

echo "> Installing Docker network loopback"

# Loopback filename
filename="com.jamesblanksby.loopback.plist"

# Loopback source/target file paths
source="./config/developer/$filename"
target="/Library/LaunchDaemons/$filename"

# Check whether loopback exists
if [[ ! -f $target ]]; then
    # Add loopback to file system
    sudo cp "$source" "$target"

    # Set file ownership and launch daemon
    sudo chown root:wheel "$target" && sudo launchctl load "$target"
fi
