#!/usr/bin/env bash

# Create developer server envrionment

echo "> Creating developer server envrionment"

directory="$HOME/Developer"

if [[ ! -d "$directory" ]]; then
    mkdir "$directory"
fi

rsync -aqh \
    --no-perms \
    "./storage/developer/Server/" "$directory/"
