#!/usr/bin/env bash

# Procesing command line tools via Yarn

echo "> Procesinging command line tools via Yarn"

# Upgrade packages to their latest version
yarn upgrade

# Add Gulp globally
yarn global add gulp
