#!/usr/bin/env bash

# Processing command line tools via Yarn

echo "> Processing command line tools via Yarn"

# Upgrade packages to their latest version
yarn upgrade

# Add Gulp globally
yarn global add gulp
